# DO NOT USE THIS IN PRODUCTION.
apiVersion: v1
kind: Secret
metadata:
  annotations:
    projectName: interval
  labels:
    app: brigade
    component: project
    heritage: brigade
  name: brigade-3fe1406a8254afd471de2bdd53483501f947004cd3d174e6a60764
stringData:
  defaultScript: |
    const { events } = require("brigadier");

    events.on("interval", (e, p) => {
        console.log("Triggered by 'interval' event.")
    });
data:
  allowHostMounts: ZmFsc2U=
  allowPrivilegedJobs: ZmFsc2U=
  brigadejsPath: ""
  buildStorageSize: ""
  cloneURL: aHR0cHM6Ly9naXRodWIuY29tL2JyaWdhZGVjb3JlL2VtcHR5LXRlc3RiZWQuZ2l0
  defaultScriptName: ""
  genericGatewaySecret: ckU5a3g=
  github.baseURL: ""
  github.token: ""
  github.uploadURL: ""
  imagePullSecrets: ""
  initGitSubmodules: ZmFsc2U=
  kubernetes.allowSecretKeyRef: ZmFsc2U=
  kubernetes.buildStorageClass: ""
  kubernetes.cacheStorageClass: ""
  namespace: ZGVmYXVsdA==
  repository: Z2l0aHViLmNvbS9icmlnYWRlY29yZS9lbXB0eS10ZXN0YmVk
  secrets: e30=
  serviceAccount: ""
  sharedSecret: ""
  sshKey: ""
  vcsSidecar: ""
  worker.name: ""
  worker.pullPolicy: SWZOb3RQcmVzZW50
  worker.registry: ""
  worker.tag: ""
  workerCommand: ""
type: brigade.sh/project
