apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "tinygw.fullname" . }}
  labels:
{{ include "tinygw.labels" . | indent 4 }}

{{ if .Values.enableRBAC }}
---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ template "tinygw.fullname" . }}
  labels:
{{ include "tinygw.labels" . | indent 4 }}
rules:
- apiGroups: [""]
  resources: ["*"]
  verbs: ["*"]

---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ template "tinygw.fullname" . }}
  labels:
{{ include "tinygw.labels" . | indent 4 }}
subjects:
- kind: ServiceAccount
  name: {{ template "tinygw.fullname" . }}
  namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: {{ template "tinygw.fullname" . }}
  apiGroup: ""
{{ end }}